### ISSUE TITLE
Document behaviour around adult content search

### ISSUE THREAD

**Issue by victorhooi** [verybada/rarbgapi#11]
By default - I believe adult content is excluded from the search results, correct?

Confirming this is intended behaviour?

You need to explicitly set the category to CATEGORY_ADULT to get any results.

Is it worth documenting this?

**Comment by verybada** [comment]
Yes, adult context are excluded by default until you set category.
I think common usage is that caller always given what they want during query, thus, I think it is not necessary to write this down.
