### ISSUE TITLE
How do you paginate through results? (Appears to only return max 25 results always).

### ISSUE THREAD

**Issue by victorhooi** [verybada/rarbgapi#13]
Is there some way to paginate through multiple pages of results with this library?

For some reason, no matter what I set limit to - client.search() will only return 25 results.

However, it's not clear how you get to page 2, page 3 etc of results?

**Comment by victorhooi** [comment]
Hmm, I saw this other issue on one of your other projects, which mentions pagination with the torrentapi SPEC:

https://github.com/verybada/rarbgsubscriber/issues/9

Are they saying there isn't pagination at all...and that you're just limited to the top results? I'm a little confused, they seem quite curt in their responses.

**Comment by verybada** [comment]
Yes, that's the limitation of RARBG's API, caller can only get last N torrents from every request.

**Comment by verybada** [comment]
> For some reason, no matter what I set limit to - client.search() will only return 25 results.
> 
Please show some example about limit parameter not work.
