### ISSUE TITLE
Search function does not appear to support specifying limit (hardcoded to 25)

### ISSUE THREAD

**Issue by victorhooi** [verybada/rarbgapi#15]
So for list(), you can pass through a limit parameter, which can be 25, 50, 100, according to the docs.

However, for search(), specifying limit doesn't seem to work (i.e. it always returns 25 results).

Looking at the source, I can't see any limit parameter for query (search) Is that by design?

**Comment by verybada** [comment]
Please show me the example about how you use search function.
Seems limit parameter still work in my test
```
>>> len(client.search(limit=100))
100
```

**Comment by verybada** [comment]
No response
