### ISSUE TITLE
Api sometimes stops working 

### ISSUE THREAD

**Issue by Skolastico** [verybada/rarbgapi#16]
this is probably a problem from my code but when try to run this code sometimes it gives me an error and it says, but when i restart it it goes back to normal.
what could i do to not show that error ? 

> Traceback (most recent call last):
  File "h:/NS/test.py", line 12, in <module>
    torrent = torrents[x]
IndexError: list index out of range

code:

```
import rarbgapi
import json
from termcolor import colored

torrentname = input("What do you wanna search for? ")
client = rarbgapi.RarbgAPI()
torrents = client.search(format_='json_extended',
                         search_string=torrentname)
for x in range(0, 5):
    torrent = torrents[x]
    realtitle = torrent._raw['title']
    title = str(realtitle)
    print(colored(title.split(), 'yellow') + '\n')
    print('Seeders: ' + str(torrent._raw['seeders']) +
          '\n' + 'Leechers: ' + str(torrent._raw['leechers']))
    print(colored(torrent._raw['download'], ) + '\n\n') 
```

**Comment by verybada** [comment]
You should check what you get before using it. 
What do you mean 'restart'? search the same name again? if yes, can you show me an example that can reproduce this issue?

**Comment by Skolastico** [comment]
Hey! 
Yes when i get that error the only way to "fix" it is to restart the code.
For example if i tried to search for "Blacklist" on the api for the first time it gives me that error but when i restart it runs perfectly. One of the things that i thought was the fact was that rarbg uses a captcha when it detects abnormalities ( [example](https://i.imgur.com/cSNi8FZ.png) here's an example) maybe is what's causing the code to get an error

**Comment by verybada** [comment]
Hi @Skolastico ,
The reason is that you don't check the search response before using it, client.search() may return an empty array once no torrent is found.

You should iterate torrents instead of use fixed value of loop like
``` python
for torrent in torrents:
    // do something
```

**Comment by verybada** [comment]
I guess they did some throttle in server side, the API always return `no results error` after I made some requests.
