### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by hl2guide** [verybada/rarbgapi#19]
For me I can't get it working on Windows:

```
import os
import rarbgapi
# options = {'retries': 10}
client = rarbgapi.RarbgAPI()
client.search(search_string="Twenty One Pilots", categories=[rarbgapi.RarbgAPI.CATEGORY_MUSIC_FLAC])
for torrent in client.list(limit=5):
    print(torrent)
os.system('pause')
```

I just get the latest torrents as results with no search term, categorization or limit applied.

Is this repo still working?

**Comment by verybada** [comment]
you should iter the response of search not list

**Comment by hl2guide** [comment]
Ok I've changed it to:

```
import os
import rarbgapi
client = rarbgapi.RarbgAPI()
results = client.search(search_string="walking dead")
for torrent_item in results:
    print(torrent_item)
os.system('pause')
```

It now returns results but very infrequently and unreliably. (1 out of 15 times run)

No error is shown for blank results.
