### ISSUE TITLE
Can't accsess to the seeders or the size 

### ISSUE THREAD

**Issue by zeddo123** [verybada/rarbgapi#4]
hello ! ,
i m new to this API , can you help i can't accsess to the seeders or the size option of the Torrent class

**Comment by verybada** [comment]
Hi @zeddo123,

Can you show some detail about the problem? like the name of the torrent that you can't get size?

**Comment by zeddo123** [comment]
hello @verybada ,
in all the search that i do , when i try to print the size "print torrent.size" the script print "none"
here is the script : https://imgur.com/a/VSqJr
here is the execution : https://imgur.com/a/fSgZH

**Comment by verybada** [comment]
hi @zeddo123 ,

let format_='json_extended' during searching may help you

**Comment by zeddo123** [comment]
no it doesn't work

**Comment by verybada** [comment]
Here are results I got, do you use the same way to get torrents?
```
>>> l = r.search('the walking dead 1080p', format_='json_extended')
>>> l[0].is_extended
True
>>> print l[0], l[0].size
The.Walking.Dead.S08E05.PROPER.1080p.WEB.h264-SKGTV[rartv](TV HD Episodes) 4915433368
>>> l = r.search('Vikings 1080p', format_='json_extended')
>>> print l[0], l[0].size
Vikings.S05E06.The.Message.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv](TV HD Episodes) 2623579826
>>>
```

**Comment by zeddo123** [comment]
https://imgur.com/a/EzQE9
i did the same thing

**Comment by verybada** [comment]
@zeddo123,
 can you post l[0].raw?

**Comment by verybada** [comment]
no response
