### ISSUE TITLE
Search in API

### ISSUE THREAD

**Issue by Matheuscruztj** [verybada/rarbgapi#7]
Hi,
I am new using your API. Can you show some usages of search?
Simple search, order by seed, how to get download link.

Thank you.

**Comment by verybada** [comment]
I have added some document, please feel free to contact me you still have some problem.

**Comment by Dr0bac** [comment]
@verybada hi!
I'm also want to know how to order torrents by seed and other similar functions. Where is that document that you mentioned where this is explained. 
Thanks

Edit: i figured it.
