### ISSUE TITLE
Grab torrent for last 10 days?

### ISSUE THREAD

**Issue by Dr0bac** [verybada/rarbgapi#9]
I want to grab torrents sorted by seeders for last 10 days?
Want to simulate this page - [rarbg top 100](https://rarbg2020.org/top100.php?category[]=14&category[]=15&category[]=16&category[]=17&category[]=21&category[]=22&category[]=42&category[]=44&category[]=45&category[]=46&category[]=47&category[]=48)
is there a function to achieve that?

i can do it myself but with this way i'm only left with ~20 torrents

````
from datetime import datetime, timedelta
import rarbgapi

torrent_list = []

client = rarbgapi.RarbgAPI()
for torrent in client.list(sort='seeders', category=44, limit=100, format_='json_extended'):
    torrent_date = datetime.strptime(torrent._raw['pubdate'], '%Y-%m-%d %H:%M:%S +0000')
    date = datetime.now() - timedelta(days=10)
    if torrent_date > date:
        torrent_list.append(torrent)

print(len(torrent_list))

>>> 20
````

Or can i access next 100 torrents (next page) after my first request and put these two requests in one list?

**Comment by verybada** [comment]
Hi @Dr0bac 
There is no pagination, their API can only return last N (up to 100) torrents in every query.
